### ISSUE TITLE
 Problem with kaddex swap

### ISSUE THREAD

**Issue by felixzou83** [kaddex-org/swap-v2#15]
After clicking send transaction button, there is no result.
Connecting the zelcore and chainweaver wallets is the same result.
Please refer to the attached screen recording.

https://user-images.githubusercontent.com/65218934/141315568-8f27a399-84bc-437c-9d17-e7e95a00b975.mp4

**Comment by kaddex-org** [comment]
We are aware and have fixed this issue, thank you for the heads up. 
The issue was a change to the gas fee requirements on the Kadena side.
