### ISSUE TITLE
my swap page showing blank page 

### ISSUE THREAD

**Issue by abuvanth** [kaddex-org/swap-v2#152]
https://swap.kaddex.com/my-swap 

Expected - list of my swaps

Actual output -  Blank page

![Screenshot 2022-08-19 at 12 31 06 PM](https://user-images.githubusercontent.com/20999104/185562491-85991fe0-4258-4548-a6af-1e74d7aa11a0.png)

Console error

![Screenshot 2022-08-19 at 12 32 16 PM](https://user-images.githubusercontent.com/20999104/185562543-63728dbd-0f2b-433a-8b5f-4048b985cf2e.png)

**Comment by peppinho89** [comment]
Hi @abuvanth thanks for the report. We fixed the issue, already merged in stage: https://github.com/kaddex-org/swap-v2/pull/153/commits

Will be pushed on production in the next release, after the end of the test phase.
