### ISSUE TITLE
Problem with adding liquidity

### ISSUE THREAD

**Issue by liquidityqloud** [kaddex-org/swap-v2#8]
In this example added 15.0 KDA and the quivalent in FLUX was a long number in the decimals. This resulted in an error
![image](https://user-images.githubusercontent.com/79758400/127770942-203f9edd-c776-4034-8546-ecfbe88ab7f2.png)
![image](https://user-images.githubusercontent.com/79758400/127770946-f387cd61-9b06-4cab-b99e-d7dba22fbfef.png)

**Comment by pomata** [comment]
@felixangelini probably precisions do not get switched
